import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <input type="checkbox" id="nav-toggle" />
          <label htmlFor="nav-toggle" className="nav-toggle-label">
            ☰ Menu
          </label>

          <ul className="nav-menu">
            <li><a href="/">Home</a></li>
            <li><a href="#groups">Groups</a></li>
            <li><a href="#payments">Payments</a></li>
            <li><a href="#about">About</a></li>
          </ul>
        </nav>

        {children}
      </body>
    </html>
  );
}